Aquarium Console App
redeyens/neb-ri-bice pull request #7
Opened 2019-08-20 06:22 UTC by GoranAlasov

Solved according to issue #3.

2019-08-20 09:17 UTC, redeyens requested changes

2019-08-20 09:17 UTC, redeyens commented on .gitignore
> +bin
Dodali smo bin i obj u .gitignore da ne bismo dodavali output fajlove na repozitorijum

2019-08-20 09:24 UTC, redeyens requested changes
Opšti utisak je da je prilično kompleksno. Zapravo ne razumem kako daje približne rezultate za ovih par primera koje sam probao.

U pojedinostima, glavne primedbe su:
- const int GravityAcceleration se nigde ne koristi
- double bendingStressAllowed = CalculateBendingStressAllowed(SafetyFactor); - ispada da je konstanta a računa se kao promenljiva sa nekim magičnim brojem
- double volume = CalculateVolume se nigde ne koristi
- CalculateSideGlassThicknessAndDeflection radi dve stvari, to bi trebalo razdvojiti
- WaterPressure ti je konstanta iako zavisi od visine vodenog stuba
- U ispisu dimenzija imaš "are {width} mm (base) x {depth} mm (base)" - šta je base?
- Površina se obično daje u kvadratnim metrima, ne u kv cm
- Niko ti nije tražio zapreminu stakla
- Na dva mesta koristiš pattern matching switch ali nepravilno :), u when treba da koristiš taj x koji si ispred deklarisao

Pokušaj da zamisliš da ti ovo čitaš za jedno 6 meseci, bez dodatne dokumentacije. Da li bi iz ovog koda bio u stanju da razumeš šta se dešava? Probaj da uradiš ceo proračun ručno, na papiru. Svaki korak koji tamo uradiš verovatno teba da ima ekvivalent i u kodu. Ako tebi nije jasno kako se ovo računa onda slobodno pitaj pa da probamo zajedno da rastumačimo. Ovako kako je sad je prilično konfuzno i ja nisam baš razumeo čak ni sa pratećom dokumentacijom.

2019-08-20 13:37 UTC, GoranAlasov commented
> Opšti utisak je da je prilično kompleksno. Zapravo ne razumem kako daje približne rezultate za ovih par primera koje sam probao. - _REZULTATI SU PRIBLIZNI ZATO STO SAM ZAOKRUZIVAO "beta" INTERVALE U CASE-OVIMA, A NISAM KORISTIO INTERPOLACIJU._
> 
> U pojedinostima, glavne primedbe su:
> 
> * const int GravityAcceleration se nigde ne koristi - _OBRISANA_
> * double bendingStressAllowed = CalculateBendingStressAllowed(SafetyFactor); - ispada da je konstanta a računa se kao promenljiva sa nekim magičnim brojem - _METODA ZAMENJENA KONSTANTOM_
> * double volume = CalculateVolume se nigde ne koristi - _ISKORISTIO U PrintResult_
> * CalculateSideGlassThicknessAndDeflection radi dve stvari, to bi trebalo razdvojiti - _POTPUNO UKLONJENA FUNKCIONALNOST ZA Deflection_
> * WaterPressure ti je konstanta iako zavisi od visine vodenog stuba - _IZMENJENO_
> * U ispisu dimenzija imaš "are {width} mm (base) x {depth} mm (base)" - šta je base? - _BASE OZNAČAVA DIMENZIJE OSNOVE AKVARIJUMA, HEIGHT OZNAČAVA VISINU. ČITLJIVIJE JE TAKO._
> * Površina se obično daje u kvadratnim metrima, ne u kv cm - _IZMENJENO_
> * Niko ti nije tražio zapreminu stakla - _OBRISANA FUNKCIONALNOST_
> * Na dva mesta koristiš pattern matching switch ali nepravilno :), u when treba da koristiš taj x koji si ispred deklarisao - _ISPRAVLJENO_
> 
> Pokušaj da zamisliš da ti ovo čitaš za jedno 6 meseci, bez dodatne dokumentacije. Da li bi iz ovog koda bio u stanju da razumeš šta se dešava? Probaj da uradiš ceo proračun ručno, na papiru. Svaki korak koji tamo uradiš verovatno teba da ima ekvivalent i u kodu. Ako tebi nije jasno kako se ovo računa onda slobodno pitaj pa da probamo zajedno da rastumačimo. Ovako kako je sad je prilično konfuzno i ja nisam baš razumeo čak ni sa pratećom dokumentacijom.

2019-08-21 08:49 UTC, redeyens commented on Program.cs
> +            double frontAndBackThicknessDeflection = CalculateSideGlassThickness(height, width, bendingStressAllowed);
Naziv više ne odgovara sadržaju. Ovo bi trebalo ispraviti da ne unosi zabunu. Možeš koristiti Rename (u VSCode F2) da bezbedno promeniš ime.

2019-08-21 08:50 UTC, redeyens submitted a review, later dismissed
Mnogo bolje od prve verzije.

2019-08-21 08:56 UTC, redeyens approved these changes
Resolved merge conflicts.

2019-08-21 08:58 UTC, merged